[[redirects]]
from = "/kegelbahn"
to = "https://bbb.kalk.space/b/kal-kpg-ink"
status = 301
force = true

[[redirects]]
from = "/coc"
to = "https://discuss.kalk.space/t/code-of-conduct/262"
status = 301
force = true

[[redirects]]
from = "/events.ics"
to = "https://ical.k3s.kalk.space/"
status = 200
force = true

[[redirects]]
from = "/cryptoparty-handout"
to = "https://md.chaosdorf.de/JmDWn-BxSC6co6P1UZbG8g?view="
status = 301
force = true
